name: Python

on: workflow_dispatch




jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        
    
    steps:
        - name: Make a File
          run: echo ${{ matrix.python-version }} > python.txt
        - name: Accidentally upload to the same artifact via multiple jobs
          uses: actions/upload-artifact@v3
          with:
              name: artifact
              path: ${{ github.workspace }}
              
        
        

    
